#defaultView:BarChart
SELECT ?protein ?proteinLabel (COUNT(?work) AS ?count) WHERE {
  ?protein wdt:P703 wd:Q82069695 ; wdt:P31 wd:Q8054 .
  ?work wdt:P921 ?protein .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,en". }
} GROUP BY ?protein ?proteinLabel
  ORDER BY ASC(?proteinLabel)
