SELECT DISTINCT ?vaccine ?vaccineLabel ?announcement WHERE {
  ?vaccine wdt:P279 wd:Q87719492 .
  OPTIONAL { ?vaccine wdt:P6949 ?announcement . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,en". }
} ORDER BY ASC(?vaccine) ASC(?announcement)
